name: Build APK for React app

on:
  push:
    branches:
      - main  # یا هر برنچی که می‌خواهی روی اون ساخت انجام بشه

jobs:
  build:
    runs-on: ubuntu-latest  # استفاده از سیستم عامل Ubuntu در GitHub Actions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # این مرحله پروژه رو از مخزن GitHub چک‌اوت می‌کنه

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'  # نسخه Node.js که پروژه به اون نیاز داره

    - name: Install dependencies
      run: |
        npm install  # نصب وابستگی‌ها
        npm run build  # ساخت اپلیکیشن React در فولدر dist

    - name: Install Capacitor
      run: |
        npm install @capacitor/core @capacitor/cli  # نصب Capacitor
        npm install @capacitor/android  # نصب پلتفرم اندروید برای Capacitor
        npx cap sync  # همگام‌سازی پروژه با Capacitor

    - name: Set up Android SDK
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk  # نصب Java Development Kit
        sudo apt install -y android-sdk  # نصب Android SDK
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools  # تنظیم محیط Android SDK

    - name: Build APK (without Android Studio)
      run: |
        cd android  # رفتن به پوشه اندروید
        ./gradlew assembleRelease  # ساخت فایل APK در حالت release
